2024-04-12 11:14:53,222 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-12 11:14:53,222 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Configure stats pid to 17900
2024-04-12 11:14:53,222 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Nam\.config\wandb\settings
2024-04-12 11:14:53,222 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Loading settings from d:\2024\AIO\Outside-Content\40-Days-Code\40-Days-Basic-Python\Day-38\wandb\settings
2024-04-12 11:14:53,222 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-12 11:14:53,222 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-12 11:14:53,223 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-12 11:14:53,223 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-12 11:14:53,223 INFO    MainThread:17900 [wandb_init.py:_log_setup():521] Logging user logs to d:\2024\AIO\Outside-Content\40-Days-Code\40-Days-Basic-Python\Day-38\wandb\run-20240412_111453-zs32xn5u\logs\debug.log
2024-04-12 11:14:53,223 INFO    MainThread:17900 [wandb_init.py:_log_setup():522] Logging internal logs to d:\2024\AIO\Outside-Content\40-Days-Code\40-Days-Basic-Python\Day-38\wandb\run-20240412_111453-zs32xn5u\logs\debug-internal.log
2024-04-12 11:14:53,223 INFO    MainThread:17900 [wandb_init.py:_jupyter_setup():467] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001DAD8066660>
2024-04-12 11:14:53,223 INFO    MainThread:17900 [wandb_init.py:init():561] calling init triggers
2024-04-12 11:14:53,223 INFO    MainThread:17900 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning-rate': 0.01, 'epochs': 1000}
2024-04-12 11:14:53,223 INFO    MainThread:17900 [wandb_init.py:init():586] re-initializing run, found existing run on stack: r8rt12t9
2024-04-12 11:14:53,227 INFO    MainThread:17900 [wandb_run.py:_finish():2064] finishing run lenam1072004/day-38-remake/r8rt12t9
2024-04-12 11:14:53,227 INFO    MainThread:17900 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-12 11:14:53,227 INFO    MainThread:17900 [wandb_run.py:_restore():2287] restore
2024-04-12 11:14:53,227 INFO    MainThread:17900 [wandb_run.py:_restore():2293] restore done
2024-04-12 11:14:57,635 INFO    MainThread:17900 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-04-12 11:14:57,635 INFO    MainThread:17900 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-04-12 11:14:57,646 INFO    MainThread:17900 [wandb_run.py:_footer_sync_info():3895] logging synced files
2024-04-12 11:14:57,814 INFO    MainThread:17900 [wandb_init.py:init():611] starting backend
2024-04-12 11:14:57,814 INFO    MainThread:17900 [wandb_init.py:init():615] setting up manager
2024-04-12 11:14:57,821 INFO    MainThread:17900 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-04-12 11:14:57,821 INFO    MainThread:17900 [wandb_init.py:init():623] backend started and connected
2024-04-12 11:14:57,831 INFO    MainThread:17900 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-12 11:14:57,831 INFO    MainThread:17900 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-12 11:14:57,831 INFO    MainThread:17900 [wandb_init.py:init():715] updated telemetry
2024-04-12 11:14:57,876 INFO    MainThread:17900 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-12 11:14:59,767 INFO    MainThread:17900 [wandb_run.py:_on_init():2357] communicating current version
2024-04-12 11:15:00,461 INFO    MainThread:17900 [wandb_run.py:_on_init():2366] got version response 
2024-04-12 11:15:00,461 INFO    MainThread:17900 [wandb_init.py:init():799] starting run threads in backend
2024-04-12 11:15:12,805 INFO    MainThread:17900 [wandb_run.py:_console_start():2335] atexit reg
2024-04-12 11:15:12,805 INFO    MainThread:17900 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-04-12 11:15:12,805 INFO    MainThread:17900 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-04-12 11:15:12,805 INFO    MainThread:17900 [wandb_run.py:_redirect():2280] Redirects installed.
2024-04-12 11:15:12,805 INFO    MainThread:17900 [wandb_init.py:init():842] run started, returning control to user process
2024-04-12 11:15:13,766 INFO    MainThread:17900 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-12 11:15:13,766 INFO    MainThread:17900 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-12 11:15:49,789 INFO    MainThread:17900 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-12 11:15:49,795 INFO    MainThread:17900 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-12 11:15:49,795 INFO    MainThread:17900 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-12 11:15:51,032 INFO    MainThread:17900 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-12 11:15:51,037 INFO    MainThread:17900 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-12 11:15:51,037 INFO    MainThread:17900 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-12 11:15:51,061 INFO    MainThread:17900 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-12 11:15:51,069 INFO    MainThread:17900 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-12 11:15:51,070 INFO    MainThread:17900 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-12 11:16:00,397 INFO    MainThread:17900 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-12 11:16:00,402 INFO    MainThread:17900 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-12 11:16:00,402 INFO    MainThread:17900 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-12 11:16:00,424 INFO    MainThread:17900 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-12 11:16:00,432 INFO    MainThread:17900 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-12 11:16:00,432 INFO    MainThread:17900 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-12 11:16:06,139 INFO    MainThread:17900 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-12 11:16:06,145 INFO    MainThread:17900 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-12 11:16:06,145 INFO    MainThread:17900 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-12 11:16:12,160 INFO    MainThread:17900 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-12 11:16:12,177 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-12 11:16:12,177 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Configure stats pid to 17900
2024-04-12 11:16:12,177 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Nam\.config\wandb\settings
2024-04-12 11:16:12,177 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Loading settings from d:\2024\AIO\Outside-Content\40-Days-Code\40-Days-Basic-Python\Day-38\wandb\settings
2024-04-12 11:16:12,178 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-12 11:16:12,178 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-12 11:16:12,178 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-12 11:16:12,178 INFO    MainThread:17900 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-12 11:16:12,179 INFO    MainThread:17900 [wandb_init.py:_log_setup():521] Logging user logs to d:\2024\AIO\Outside-Content\40-Days-Code\40-Days-Basic-Python\Day-38\wandb\run-20240412_111612-zuwa2qop\logs\debug.log
2024-04-12 11:16:12,179 INFO    MainThread:17900 [wandb_init.py:_log_setup():522] Logging internal logs to d:\2024\AIO\Outside-Content\40-Days-Code\40-Days-Basic-Python\Day-38\wandb\run-20240412_111612-zuwa2qop\logs\debug-internal.log
2024-04-12 11:16:12,179 INFO    MainThread:17900 [wandb_init.py:init():561] calling init triggers
2024-04-12 11:16:12,179 INFO    MainThread:17900 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning-rate': 0.01, 'epochs': 1000}
2024-04-12 11:16:12,179 INFO    MainThread:17900 [wandb_init.py:init():586] re-initializing run, found existing run on stack: zs32xn5u
2024-04-12 11:16:12,182 INFO    MainThread:17900 [wandb_run.py:_finish():2064] finishing run lenam1072004/day-38-remake/zs32xn5u
2024-04-12 11:16:12,182 INFO    MainThread:17900 [jupyter.py:save_history():445] not saving jupyter history
2024-04-12 11:16:12,183 INFO    MainThread:17900 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-12 11:16:12,183 INFO    MainThread:17900 [wandb_init.py:_jupyter_teardown():449] cleaning up jupyter logic
2024-04-12 11:16:12,183 INFO    MainThread:17900 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-12 11:16:12,183 INFO    MainThread:17900 [wandb_run.py:_restore():2287] restore
2024-04-12 11:16:12,184 INFO    MainThread:17900 [wandb_run.py:_restore():2293] restore done
2024-04-12 11:16:16,551 INFO    MainThread:17900 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-04-12 11:16:16,551 INFO    MainThread:17900 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-04-12 11:16:16,567 INFO    MainThread:17900 [wandb_run.py:_footer_sync_info():3895] logging synced files
